name = "tampkemail-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
vars = { NODE_VERSION = "22", BRIDGE_URL = "https://tampkmail-bridge-1.onrender.com" }

[env.preview]
vars = { NODE_VERSION = "22", BRIDGE_URL = "https://tampkmail-bridge-1.onrender.com" }
